[workspace]
members = [
    "crates/*",
    "apps/*"
]
resolver = "3"

[workspace.dependencies]
iam = { path = "crates/iam" }
communities = { path = "crates/communities" }
shared = { path = "crates/shared" }